
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# vim bindings for switching between panes
# bind -n M-h select-pane -L
# bind -n M-l select-pane -R
# bind -n M-k select-pane -U
# bind -n M-j select-pane -D
#
# bind -n C-M-h resize-pane -L 1
# bind -n C-M-j resize-pane -D 1
# bind -n C-M-k resize-pane -U 1
# bind -n C-M-l resize-pane -R 1
#
# bind -n M-H swap-pane -s :. -t '{left-of}'
# bind -n M-J swap-pane -s :. -t '{down-of}'
# bind -n M-K swap-pane -s :. -t '{up-of}'
# bind -n M-L swap-pane -s :. -t '{right-of}'

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'

bind-key -n C-M-h if-shell "$is_vim" 'send-keys C-M-h' 'resize-pane -L 1'
bind-key -n C-M-j if-shell "$is_vim" 'send-keys C-M-j' 'resize-pane -D 1'
bind-key -n C-M-k if-shell "$is_vim" 'send-keys C-M-k' 'resize-pane -U 1'
bind-key -n C-M-l if-shell "$is_vim" 'send-keys C-M-l' 'resize-pane -R 1'

bind-key -n M-H if-shell "$is_vim" 'send-keys M-H' "swap-pane -s :. -t '{left-of}'"
bind-key -n M-J if-shell "$is_vim" 'send-keys M-J' "swap-pane -s :. -t '{down-of}'"
bind-key -n M-K if-shell "$is_vim" 'send-keys M-K' "swap-pane -s :. -t '{up-of}'"
bind-key -n M-L if-shell "$is_vim" 'send-keys M-L' "swap-pane -s :. -t '{right-of}'"


bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

setw -g mode-keys vi

# Explicit vim-style selection in copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Use Alt+number to switch windows
set -g base-index 1
run-shell 'for i in $(seq 1 9); do \
  tmux bind-key -n M-$i if-shell "tmux select-window -t $i" "" "new-window -t $i"; \
done'


set -g pane-active-border-style "bg=default,fg=blue"
set-option -g status-position "bottom"
set-option -g status-style bg=default,fg=default
set-option -g status-justify "centre"
set-option -g window-status-format " #I:#W "
set-option -g window-status-format " #I:#W #{?window_zoomed_flag, 󰊓 }"

set-option -g window-status-current-format "#[bg=blue,fg=white] #I:#W "
