font_family                 JetBrainsMono Nerd Font
font_size                   11
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
# background_opacity          0.8
background                  #1B1B1B
selection_foreground        none
selection_background        none
hide_window_decorations     no
disable_ligatures always
term xterm-256color
map ctrl+n new_os_window_with_cwd



# BEGIN_KITTY_THEME
# Noctalia
# include current-theme.conf
# END_KITTY_THEME
